### ISSUE TITLE
故障重现功能实现原理？

### ISSUE THREAD

**Issue by ljwango** [tobegit3hub/note#4]
您好！我看了你写的关于failover的文档，有几个问题想咨询下，故障重现功能是怎么实现的呢？我看了很多其他的分布式测试工具，在实现故障重现时，都是使用的快照来实现的，但是failover好像不是使用的快照，能否将此模块的实现原理向我介绍下？
    谢谢！

**Comment by tobegit3hub** [comment]
论文提及的故障重现是通过记录action的步骤来实现的，我们会随机生成模拟故障的action列表和时间间隔，如果测试国外检测到故障就会自动重复执行以上的action列表，进而重现故障。

**Comment by ljwango** [comment]
是不是记录测试步骤，然后通过测试步骤来实现故障重现？但是这样的话，有的故障不一定能够重现吧？

**Comment by tobegit3hub** [comment]
是的，确实有可能不能重现的。 @ljwango
